name: phone_number_example
description: Demonstrates how to use the phone_number plugin.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  crud_test:
    path: ../

  intl: ^0.17.0
  get_it: ^7.2.0
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  loading_animation_widget: ^1.2.0+1
  equatable: ^2.0.5
  floor: ^1.4.1
  mockito: ^5.2.0
  bloc_test: ^9.0.3
  flutter_gherkin: ^2.0.0
  glob: ^2.0.0
dev_dependencies:
  integration_test:
  flutter_test:
    sdk: flutter
  lint: ^1.10.0
  floor_generator: ^1.3.0
  build_runner: ^2.1.2
flutter:
  uses-material-design: true
