name: crud_test
description: Flutter plugin for parsing, formatting and validating international
  phone numbers.
version: 1.0.0
homepage: https://github.com/nashfive/phone_number

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.7.0
  rxdart: ^0.24.1

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.julienvignali.phone_number
        pluginClass: PhoneNumberPlugin
      ios:
        pluginClass: PhoneNumberPlugin
